import {
  MunicipalZone,
  SanitationWorker,
  WasteReport,
  AuditLog,
  InAppNotification,
} from '../types';

export const SEED_ZONES: MunicipalZone[] = [
  {
    id: 'zone-central',
    name: 'Sector 1 — Commercial & Market District',
    city: 'Metro City',
    supervisorName: 'Marcus Vance',
    supervisorEmail: 'marcus.vance@cleanspot.org',
    activeTeamsCount: 4,
    center: { latitude: 13.0827, longitude: 80.2707 },
  },
  {
    id: 'zone-north',
    name: 'Sector 2 — University & Transit Hub',
    city: 'Metro City',
    supervisorName: 'Elena Rostova',
    supervisorEmail: 'elena.rostova@cleanspot.org',
    activeTeamsCount: 3,
    center: { latitude: 13.0982, longitude: 80.2825 },
  },
  {
    id: 'zone-east',
    name: 'Sector 3 — Waterfront & Marina Boulevard',
    city: 'Metro City',
    supervisorName: 'David Chen',
    supervisorEmail: 'david.chen@cleanspot.org',
    activeTeamsCount: 3,
    center: { latitude: 13.0475, longitude: 80.2824 },
  },
  {
    id: 'zone-south',
    name: 'Sector 4 — Residential Parks & Green Belt',
    city: 'Metro City',
    supervisorName: 'Amina Al-Mansoor',
    supervisorEmail: 'amina.m@cleanspot.org',
    activeTeamsCount: 2,
    center: { latitude: 13.0102, longitude: 80.2158 },
  },
];

export const SEED_WORKERS: SanitationWorker[] = [
  {
    id: 'worker-01',
    name: 'Rajan Kumar',
    email: 'rajan.kumar@cleanspot.org',
    phone: '+1-555-0192',
    zoneId: 'zone-central',
    teamId: 'team-alpha',
    teamName: 'Zone 1 Sanitation Team (Rapid Response)',
    isAvailable: true,
    currentActiveTasks: 1,
    completedTasksCount: 48,
  },
  {
    id: 'worker-02',
    name: 'Priya Murugan',
    email: 'priya.murugan@cleanspot.org',
    phone: '+1-555-0193',
    zoneId: 'zone-north',
    teamId: 'team-beta',
    teamName: 'Zone 2 Street Sweeping Unit',
    isAvailable: true,
    currentActiveTasks: 1,
    completedTasksCount: 63,
  },
  {
    id: 'worker-03',
    name: 'Arun Prakash',
    email: 'arun.prakash@cleanspot.org',
    phone: '+1-555-0194',
    zoneId: 'zone-east',
    teamId: 'team-gamma',
    teamName: 'Zone 3 Hydraulic & Debris Squad',
    isAvailable: true,
    currentActiveTasks: 0,
    completedTasksCount: 41,
  },
  {
    id: 'worker-04',
    name: 'Kavitha Sundaram',
    email: 'kavitha.s@cleanspot.org',
    phone: '+1-555-0195',
    zoneId: 'zone-south',
    teamId: 'team-delta',
    teamName: 'Zone 4 Residential Cleanup Team',
    isAvailable: true,
    currentActiveTasks: 1,
    completedTasksCount: 52,
  },
];

export const SAMPLE_PRESET_IMAGES = [
  {
    id: 'preset-bin',
    title: 'Overflowing Public Bin',
    category: 'overflowing_bin',
    url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    description: 'Community metal bin overflowing onto pedestrian sidewalk. Garbage spreading into bicycle lane.',
  },
  {
    id: 'preset-dumping',
    title: 'Vacant Plot Illegal Dumping',
    category: 'illegal_dumping',
    url: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    description: 'Discarded packaging boxes, plastic sacks, and drywall illegally fly-tipped along boundary wall.',
  },
  {
    id: 'preset-plastic',
    title: 'Plastic Bottle Accumulation',
    category: 'plastic_waste',
    url: 'https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=800&q=80',
    description: 'Dense accumulation of single-use PET drink containers and polymer carrier bags near market stalls.',
  },
  {
    id: 'preset-drain',
    title: 'Drainage Culvert Choke',
    category: 'drain_waste',
    url: 'https://images.unsplash.com/photo-1562077772-3ab1218634df?auto=format&fit=crop&w=800&q=80',
    description: 'Stormwater grate choked with floating bags and sludge causing roadway waterlogging risk.',
  },
];

export const RESOLUTION_CLEAN_IMAGE =
  'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80';

export const SEED_REPORTS: WasteReport[] = [
  {
    id: 'CS-2026-000181',
    citizenId: 'citizen-01',
    citizenName: 'Maya Sharma',
    citizenEmail: 'maya.sharma@example.com',
    imageUrls: [
      'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    ],
    category: 'overflowing_bin',
    userCategory: 'overflowing_bin',
    aiCategory: 'overflowing_bin',
    severity: 'critical',
    aiSeverity: 'critical',
    estimatedVolume: 'large',
    aiConfidence: 0.94,
    description: 'Community metal bin completely overflowing on Gandhi Road sidewalk. Garbage spreading across 15 meters, blocking pedestrians.',
    landmark: 'Opposite State Bank ATM',
    location: {
      latitude: 13.0832,
      longitude: 80.2711,
      accuracy: 8,
      formattedAddress: '42 Gandhi Road, Near Market Circle',
      approximateLocation: 'Gandhi Road (Sector 1)',
      locality: 'Sector 1 Commercial',
      city: 'Metro City',
      zoneId: 'zone-central',
    },
    zoneId: 'zone-central',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    priorityScore: 88,
    priorityReasons: ['CRITICAL severity', 'High volume', '4 supporting citizen votes'],
    assignedTeamId: 'team-alpha',
    assignedWorkerId: 'worker-01',
    assignedWorkerName: 'Rajan Kumar (Zone 1 Team)',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    communityVotes: {
      stillThere: 5,
      cleaned: 0,
      worsened: 2,
    },
    evidence: [
      {
        id: 'ev-01',
        reportId: 'CS-2026-000181',
        type: 'BEFORE',
        imageUrl:
          'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
        uploadedBy: 'citizen-01',
        uploadedRole: 'citizen',
        uploadedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
    ],
    statusHistory: [
      {
        id: 'sh-1',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'Maya Sharma',
        actorRole: 'citizen',
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-2',
        fromStatus: 'SUBMITTED',
        toStatus: 'VERIFIED',
        changedBy: 'Marcus Vance',
        actorRole: 'supervisor',
        reason: 'Confirmed critical sidewalk obstruction',
        timestamp: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-3',
        fromStatus: 'VERIFIED',
        toStatus: 'ASSIGNED',
        changedBy: 'Marcus Vance',
        actorRole: 'supervisor',
        reason: 'Assigned to Zone 1 Rapid Sanitation Team',
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-4',
        fromStatus: 'ASSIGNED',
        toStatus: 'IN_PROGRESS',
        changedBy: 'Rajan Kumar',
        actorRole: 'worker',
        reason: 'Compactor vehicle en route to incident location',
        timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'CS-2026-000182',
    citizenId: 'citizen-02',
    citizenName: 'Rahul Verma',
    citizenEmail: 'rahul.v@example.com',
    imageUrls: [
      'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    ],
    category: 'illegal_dumping',
    userCategory: 'illegal_dumping',
    aiCategory: 'illegal_dumping',
    severity: 'high',
    aiSeverity: 'high',
    estimatedVolume: 'very_large',
    aiConfidence: 0.91,
    description: 'Truck dumped commercial packaging and plaster drywall onto vacant corner parcel overnight.',
    landmark: 'Behind Metro Station Pillar 104',
    location: {
      latitude: 13.0841,
      longitude: 80.2725,
      accuracy: 12,
      formattedAddress: 'Plot 18, Station Link Avenue',
      approximateLocation: 'Station Link Avenue (Sector 1)',
      locality: 'Sector 1 Commercial',
      city: 'Metro City',
      zoneId: 'zone-central',
    },
    zoneId: 'zone-central',
    status: 'SUBMITTED',
    priority: 'HIGH',
    priorityScore: 74,
    priorityReasons: ['HIGH severity', 'Very large volume', 'Near public transit'],
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 19 * 3600 * 1000).toISOString(),
    communityVotes: {
      stillThere: 3,
      cleaned: 0,
      worsened: 0,
    },
    evidence: [],
    statusHistory: [
      {
        id: 'sh-10',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'Rahul Verma',
        actorRole: 'citizen',
        timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'CS-2026-000183',
    citizenId: 'citizen-03',
    citizenName: 'Deepa Krishnan',
    citizenEmail: 'deepa.k@example.com',
    imageUrls: [
      'https://images.unsplash.com/photo-1562077772-3ab1218634df?auto=format&fit=crop&w=800&q=80',
    ],
    category: 'drain_waste',
    userCategory: 'drain_waste',
    aiCategory: 'drain_waste',
    severity: 'critical',
    aiSeverity: 'critical',
    estimatedVolume: 'large',
    aiConfidence: 0.96,
    description: 'Stormwater inlet culvert completely blocked with plastic waste and tree branches. Rainwater backing up onto road.',
    landmark: 'Culvert near School Gate 2',
    location: {
      latitude: 13.0995,
      longitude: 80.2831,
      accuracy: 6,
      formattedAddress: '88 Campus Road, Near North School',
      approximateLocation: 'Campus Road (Sector 2)',
      locality: 'Sector 2 University',
      city: 'Metro City',
      zoneId: 'zone-north',
    },
    zoneId: 'zone-north',
    status: 'VERIFIED',
    priority: 'CRITICAL',
    priorityScore: 92,
    priorityReasons: ['CRITICAL severity', 'Drain flood hazard', 'Near school zone'],
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    dueAt: new Date(Date.now() + 1 * 3600 * 1000).toISOString(),
    communityVotes: {
      stillThere: 4,
      cleaned: 0,
      worsened: 1,
    },
    evidence: [],
    statusHistory: [
      {
        id: 'sh-20',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'Deepa Krishnan',
        actorRole: 'citizen',
        timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-21',
        fromStatus: 'SUBMITTED',
        toStatus: 'VERIFIED',
        changedBy: 'Elena Rostova',
        actorRole: 'supervisor',
        reason: 'Hydrological flooding hazard verified',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'CS-2026-000184',
    citizenId: 'citizen-04',
    citizenName: 'Anil Desai',
    citizenEmail: 'anil.desai@example.com',
    imageUrls: [
      'https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=800&q=80',
    ],
    category: 'plastic_waste',
    userCategory: 'plastic_waste',
    aiCategory: 'plastic_waste',
    severity: 'medium',
    aiSeverity: 'medium',
    estimatedVolume: 'medium',
    aiConfidence: 0.89,
    description: 'Large cluster of discarded plastic bottles and delivery bags behind vegetable market stalls.',
    landmark: 'Behind Fruit Stalls Row C',
    location: {
      latitude: 13.0482,
      longitude: 80.2819,
      accuracy: 10,
      formattedAddress: 'Marina Wholesale Market Alley',
      approximateLocation: 'Marina Market (Sector 3)',
      locality: 'Sector 3 Waterfront',
      city: 'Metro City',
      zoneId: 'zone-east',
    },
    zoneId: 'zone-east',
    status: 'RESOLVED_PENDING_CONFIRMATION',
    priority: 'MEDIUM',
    priorityScore: 44,
    assignedTeamId: 'team-gamma',
    assignedWorkerId: 'worker-03',
    assignedWorkerName: 'Arun Prakash (Zone 3 Team)',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now()).toISOString(),
    communityVotes: {
      stillThere: 1,
      cleaned: 6,
      worsened: 0,
    },
    evidence: [
      {
        id: 'ev-30',
        reportId: 'CS-2026-000184',
        type: 'BEFORE',
        imageUrl:
          'https://images.unsplash.com/photo-1528323273322-d81458248d40?auto=format&fit=crop&w=800&q=80',
        uploadedBy: 'citizen-04',
        uploadedRole: 'citizen',
        uploadedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: 'ev-31',
        reportId: 'CS-2026-000184',
        type: 'AFTER',
        imageUrl: RESOLUTION_CLEAN_IMAGE,
        uploadedBy: 'worker-03',
        uploadedRole: 'worker',
        uploadedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        notes: 'Collected 180kg plastic bottles and sent to municipal recycling center.',
        aiVerificationScore: 0.95,
        aiVerificationSummary: 'AI Visual Match: Debris cleared. Pavement is completely unobstructed.',
      },
    ],
    statusHistory: [
      {
        id: 'sh-30',
        fromStatus: 'DRAFT',
        toStatus: 'SUBMITTED',
        changedBy: 'Anil Desai',
        actorRole: 'citizen',
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-31',
        fromStatus: 'SUBMITTED',
        toStatus: 'VERIFIED',
        changedBy: 'David Chen',
        actorRole: 'supervisor',
        timestamp: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-32',
        fromStatus: 'VERIFIED',
        toStatus: 'ASSIGNED',
        changedBy: 'David Chen',
        actorRole: 'supervisor',
        timestamp: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-33',
        fromStatus: 'ASSIGNED',
        toStatus: 'IN_PROGRESS',
        changedBy: 'Arun Prakash',
        actorRole: 'worker',
        timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-34',
        fromStatus: 'IN_PROGRESS',
        toStatus: 'RESOLVED_PENDING_CONFIRMATION',
        changedBy: 'Arun Prakash',
        actorRole: 'worker',
        reason: 'Recycling sweep completed, after photo attached',
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
    ],
  },
  {
    id: 'CS-2026-000185',
    citizenId: 'citizen-05',
    citizenName: 'Fatima Zohra',
    citizenEmail: 'fatima.z@example.com',
    imageUrls: [
      'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    ],
    category: 'roadside_garbage',
    userCategory: 'roadside_garbage',
    aiCategory: 'roadside_garbage',
    severity: 'medium',
    aiSeverity: 'medium',
    estimatedVolume: 'medium',
    aiConfidence: 0.92,
    description: 'Roadside garbage bags ripped open by animals along quiet residential lane.',
    landmark: 'Corner of 4th Cross',
    location: {
      latitude: 13.0115,
      longitude: 80.2162,
      accuracy: 5,
      formattedAddress: '12 South Garden Road',
      approximateLocation: 'South Garden Road (Sector 4)',
      locality: 'Sector 4 Residential',
      city: 'Metro City',
      zoneId: 'zone-south',
    },
    zoneId: 'zone-south',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    priorityScore: 38,
    assignedTeamId: 'team-delta',
    assignedWorkerId: 'worker-04',
    assignedWorkerName: 'Kavitha Sundaram (Zone 4 Team)',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    dueAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
    citizenVerified: 'YES',
    citizenFeedback: 'Thank you! The road was thoroughly swept and sanitized.',
    communityVotes: {
      stillThere: 0,
      cleaned: 12,
      worsened: 0,
    },
    evidence: [
      {
        id: 'ev-40',
        reportId: 'CS-2026-000185',
        type: 'AFTER',
        imageUrl: RESOLUTION_CLEAN_IMAGE,
        uploadedBy: 'worker-04',
        uploadedRole: 'worker',
        uploadedAt: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
        notes: 'Area disinfected and swept clean.',
        aiVerificationScore: 0.98,
      },
    ],
    statusHistory: [
      {
        id: 'sh-40',
        fromStatus: 'IN_PROGRESS',
        toStatus: 'RESOLVED_PENDING_CONFIRMATION',
        changedBy: 'Kavitha Sundaram',
        actorRole: 'worker',
        timestamp: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
      },
      {
        id: 'sh-41',
        fromStatus: 'RESOLVED_PENDING_CONFIRMATION',
        toStatus: 'RESOLVED',
        changedBy: 'Fatima Zohra',
        actorRole: 'citizen',
        reason: 'Citizen verified: Cleaned',
        timestamp: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      },
    ],
  },
];

export const SEED_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    title: 'Report Verified',
    message: 'Your report CS-2026-000181 on Gandhi Road was verified and assigned to Zone 1 Sanitation Team.',
    reportId: 'CS-2026-000181',
    type: 'status_update',
    targetRole: 'citizen',
    read: false,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    title: 'Resolution Evidence Submitted',
    message: 'Cleanup photo uploaded for CS-2026-000184. Please verify if the waste is cleared.',
    reportId: 'CS-2026-000184',
    type: 'community',
    targetRole: 'citizen',
    read: false,
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    title: 'Critical Report Alert',
    message: 'High priority flood hazard: Drain inlet choked on Campus Road (Sector 2).',
    reportId: 'CS-2026-000183',
    type: 'critical_alert',
    targetRole: 'supervisor',
    read: false,
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    actorId: 'admin-01',
    actorName: 'Civic Admin',
    actorRole: 'admin',
    action: 'SYSTEM_BOOT',
    entityType: 'system',
    entityId: 'sys-01',
    metadata: { version: '2.0.0', platform: 'CleanSpot Core' },
    timestamp: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log-02',
    actorId: 'marcus.vance',
    actorName: 'Marcus Vance',
    actorRole: 'supervisor',
    action: 'REPORT_VERIFIED',
    entityType: 'report',
    entityId: 'CS-2026-000181',
    metadata: { priority: 'CRITICAL', slaHours: 2 },
    timestamp: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'log-03',
    actorId: 'marcus.vance',
    actorName: 'Marcus Vance',
    actorRole: 'supervisor',
    action: 'TEAM_ASSIGNED',
    entityType: 'report',
    entityId: 'CS-2026-000181',
    metadata: { team: 'Zone 1 Sanitation Team', lead: 'Rajan Kumar' },
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
];
